# Generated by Django 6.1.1 on 2026-09-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project'), ('other', 'Other')], default='final', max_length=50, verbose_name='Exam Type')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Exam Date')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marks Obtained')),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Max Marks')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
                'ordering': ['-exam_date', 'student'],
                'unique_together': {('student', 'course', 'exam_type')},
            },
        ),
    ]
