# Generated by Django 6.1.1 on 2026-09-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='Qualification')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['employee_id'],
            },
        ),
    ]
